### ISSUE TITLE
Self signed ssl filename wrong

### ISSUE THREAD

**Issue by speedmann** [nickjj/ansible-nginx#10]
Hi all,

having nginx_ssl_override_filename default to '' will always result in the generated and configured ssl certificates to be name and added to configuration like `/etc/nginx/ssl/.pem`

Removing it from defaults solves the issue, but I am not sure this is the correct way to do so

**Comment by nickjj** [comment]
That is definitely the way to do it (your way).

Thanks. This is a bug.

**Comment by carlos22** [comment]
Workaround for this is to manually add the first domain to `group_vars/app.yml`
```
nginx_ssl_override_filename: 'example.com'
```
