### ISSUE TITLE
Self-signed certs interfers with letsencrypt

### ISSUE THREAD

**Issue by ScuttleSE** [nickjj/ansible-nginx#12]
Something weird with the certs here...

First I installed the nginx-role with self-signed certs, the only way to get it up and running.

After that I did a letsencrypt-run to generate the "real" certs, but the playbook doesn't seem to replace the certs. All the sites are still using a cert for "localhost" instead of the letsencrypt one.

**Comment by nickjj** [comment]
What happens if you set `letsencrypt_force_reset_all: True`? It's `False` by default.

**Comment by ScuttleSE** [comment]
Hm, did a "manual" reset by deleting the files in /usr/local/acme-tiny, and that seemed to do the trick. Is this beacuse I did the first runs agains the test-api?

**Comment by ScuttleSE** [comment]
gotcha!
